name: CI

on:
  push:
  pull_request:

jobs:
  build-test-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build (all targets, all features)
        run: cargo build --all-targets --all-features
      - name: Test (release, all features)
        run: cargo test --release --all-features
      - name: Clippy (pedantic)
        run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::all -D clippy::pedantic -D clippy::nursery

  fuzz-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Build fuzz targets
        run: |
          cd fuzz
          cargo fuzz build registration_decode
          cargo fuzz build registration_verify


